### ISSUE TITLE
Inotify.Read() discards solo events

### ISSUE THREAD

**Issue by cruxic** [illarion/go-inotify#2]
In Inotify.Read(), if the number of bytes read is exactly one event (SizeofInotifyEvent) then the function returns an empty slice.  I think that:

```
for offset+syscall.SizeofInotifyEvent < n {
```
should be 
```
for offset+syscall.SizeofInotifyEvent <= n {
```

**Comment by illarion** [comment]
Could not reproduce... Could you please provide a test case?
