### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by scunningham** [illarion/go-inotify#4]
Hello.

There's an error here:  https://github.com/illarion/gonotify/blob/master/inotify.go#L187

`
		name = filepath.Join(i.rwatches[uint32(event.Wd)], name)
`

The 'i.rwatches' map is accessed without a lock.  If accessing this data structure from another go routine, the program panics.

**Comment by illarion** [comment]
Fixed in v2.0.2, thank you!
